// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHabCfITlZr1KCP-FQHkp6BQm1bW02iMk',
    appId: '1:602883497144:web:76aaf1f5449b2e26ba684d',
    messagingSenderId: '602883497144',
    projectId: 'casaq-database',
    authDomain: 'casaq-database.firebaseapp.com',
    storageBucket: 'casaq-database.firebasestorage.app',
    measurementId: 'G-C378GXQR9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwweyJbucC2_gjAfN2vkBR3V98jaZJyZ8',
    appId: '1:602883497144:android:b5c9ce6ac7f45964ba684d',
    messagingSenderId: '602883497144',
    projectId: 'casaq-database',
    storageBucket: 'casaq-database.firebasestorage.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMR6Dps6503yZ4h8BhLJCk1cmSZ2pEIA',
    appId: '1:602883497144:ios:32b1333845608349ba684d',
    messagingSenderId: '602883497144',
    projectId: 'casaq-database',
    storageBucket: 'casaq-database.firebasestorage.com',
    iosBundleId: 'com.casaq.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMR6Dps6503yZ4h8BhLJCk1cmSZ2pEIA',
    appId: '1:602883497144:ios:32b1333845608349ba684d',
    messagingSenderId: '602883497144',
    projectId: 'casaq-database',
    storageBucket: 'casaq-database.firebasestorage.com',
    iosBundleId: 'com.casaq.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHabCfITlZr1KCP-FQHkp6BQm1bW02iMk',
    appId: '1:602883497144:web:9bcd3c468f1b1c2aba684d',
    messagingSenderId: '602883497144',
    projectId: 'casaq-database',
    authDomain: 'casaq-database.firebaseapp.com',
    storageBucket: 'casaq-database.firebasestorage.com',
    measurementId: 'G-VFB0C1ZD1N',
  );
}
